"use client";

import React, { useEffect, useState } from "react";
import ModuleWorkspace from "../../components/dashboard/ModuleWorkspace";
import api from "@/lib/api";

export default function ReportsPage() {
    const [metrics, setMetrics] = useState([
        { title: "Published Reports", value: "...", trend: 0, status: "info" as any },
        { title: "Variance Alerts", value: "...", status: "info" as any },
        { title: "Scheduled Runs", value: "12", status: "success" as any },
        { title: "Data Freshness", value: "99.9", status: "success" as any, suffix: "%" },
    ]);
    const [tableData, setTableData] = useState<any[]>([]);

    useEffect(() => {
        const fetchReports = async () => {
            try {
                const response = await api.get("/tenants/audit-logs?action=REPORT_GENERATED");
                const logs = response.data.logs || [];

                setMetrics([
                    { title: "Generated Reports", value: logs.length.toString(), trend: 15.4, status: "success" },
                    { title: "Regulatory Filings", value: "4", status: "info" },
                    { title: "Scheduled Runs", value: "12", status: "success" },
                    { title: "Data Freshness", value: "99.9", status: "success", suffix: "%" },
                ]);

                setTableData(logs.map((l: any) => ({
                    id: l.id.substring(0, 8).toUpperCase(),
                    name: `Financial Summary - ${l.details?.format || "PDF"}`,
                    category: "Governance",
                    period: new Date(l.createdAt).toLocaleString('default', { month: 'long', year: 'numeric' }),
                    date: new Date(l.createdAt).toLocaleDateString(),
                    user: l.user?.name || "System",
                    status: "Success",
                    description: `Automated financial governance report generated in ${l.details?.format} format.`
                })));
            } catch (error) {
                console.error("Failed to fetch reports", error);
            }
        };

        fetchReports();
    }, []);

    const columns = [
        { header: "Report Name", accessor: "name" },
        { header: "Category", accessor: "category" },
        { header: "Period", accessor: "period" },
        { header: "Generated At", accessor: "date" },
        { header: "Generated By", accessor: "user" },
        { header: "Status", accessor: "status" },
    ];

    return (
        <ModuleWorkspace
            title="Financial Reporting"
            description="Generate boardroom-ready financial artifacts. Design custom report packages, automate distributions, and maintain a single source of truth."
            metrics={metrics}
            tableColumns={columns}
            tableData={tableData}
        />
    );
}
